import type { InputField } from "form-lib";

export const formMockData: readonly InputField[] = [
	{
		name: "productName",
		label: "Product name",
		type: "string",
		operators: ["contains", "equals", "startsWith", "in"],
		defaultOperator: "contains",
		defaultValue: "shampoo",
		required: true,
	},
	{
		name: "stockQuantity",
		label: "Stock quantity",
		type: "number",
		operators: ["greaterThan", "lessThan", "between", "in"],
		defaultOperator: "greaterThan",
		defaultValue: 100,
	},
	{
		name: "isActive",
		label: "Active product",
		type: "boolean",
		operators: ["equals", "notEquals"],
		defaultOperator: "equals",
		defaultValue: true,
	},
	{
		name: "createdOn",
		label: "Created on",
		type: "date",
		operators: ["greaterThanOrEqual", "lessThanOrEqual", "between"],
		defaultOperator: "greaterThanOrEqual",
		defaultValue: "2026-01-01",
	},
	{
		name: "productionTime",
		label: "Production time",
		type: "time",
		operators: ["greaterThanOrEqual", "lessThanOrEqual"],
		defaultOperator: "greaterThanOrEqual",
		defaultValue: "08:00",
	},
	{
		name: "category",
		label: "Category",
		type: "string",
		operators: ["equals", "notEquals"],
		defaultOperator: "equals",
		defaultValue: "finished-products",
		options: [
			{ label: "Raw materials", value: "raw-materials" },
			{ label: "Finished products", value: "finished-products" },
			{ label: "Packaging", value: "packaging" },
		],
	},
	{
		name: "warehouses",
		label: "Warehouses",
		type: "number",
		operators: ["in", "notIn"],
		defaultOperator: "in",
		defaultValue: [1, 3],
		multiple: true,
		options: [
			{ label: "Athens", value: 1 },
			{ label: "Thessaloniki", value: 2 },
			{ label: "Patras", value: 3 },
			{ label: "Heraklion", value: 4 },
		],
	},
	{
		name: "sqlRule",
		label: "SQL rule",
		type: "code",
		operators: ["sql", "javascript", "typescript", "json", "plaintext"],
		defaultOperator: "sql",
		defaultValue: "select product_id from products where is_active = 1;",
	},
];
