import type { MenuDataModel } from "menu-lib";

export const menuData: MenuDataModel = {
	mainHeaderText: "Manufacturing",
	subHeaderText: "System Menu",
	menuItems: [
		{
			id: "partners",
			text: "Partners",
			icon: "user-friends",
			iconColor: "text-indigo-400",
			isFolder: true,
			items: [
				{
					id: "suppliers",
					text: "Suppliers",
					icon: "truck-loading",
					iconColor: "text-amber-400",
					isFolder: true,
					items: [
						{
							id: "supplier-list",
							text: "Supplier List",
							icon: "list",
							iconColor: "text-slate-400",
							isFolder: false,
							items: [],
						},
						{
							id: "supplier-categories",
							text: "Supplier Categories",
							icon: "tags",
							iconColor: "text-pink-400",
							isFolder: false,
							items: [],
						},
						{
							id: "supplier-contracts",
							text: "Contracts",
							icon: "file-signature",
							iconColor: "text-violet-400",
							isFolder: true,
							items: [
								{
									id: "active-supplier-contracts",
									text: "Active Contracts",
									icon: "check-circle",
									iconColor: "text-green-400",
									isFolder: false,
									items: [],
								},
								{
									id: "expired-supplier-contracts",
									text: "Expired Contracts",
									icon: "times-circle",
									iconColor: "text-red-400",
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
				{
					id: "customers",
					text: "Customers",
					icon: "user-tag",
					iconColor: "text-teal-400",
					isFolder: true,
					items: [
						{
							id: "customer-list",
							text: "Customer List",
							icon: "address-book",
							iconColor: "text-blue-400",
							isFolder: false,
							items: [],
						},
						{
							id: "customer-groups",
							text: "Customer Groups",
							icon: "users",
							iconColor: "text-cyan-400",
							isFolder: false,
							items: [],
						},
						{
							id: "customer-pricing",
							text: "Pricing",
							icon: "money-bill-wave",
							iconColor: "text-emerald-400",
							isFolder: true,
							items: [
								{
									id: "price-lists",
									text: "Price Lists",
									icon: "clipboard-list",
									iconColor: "text-lime-400",
									isFolder: false,
									items: [],
								},
								{
									id: "discount-rules",
									text: "Discount Rules",
									icon: "percent",
									iconColor: "text-orange-400",
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
			],
		},
		{
			id: "products",
			text: "Products",
			icon: "box",
			iconColor: "text-orange-400",
			isFolder: true,
			items: [
				{
					id: "raw-materials",
					text: "Raw Materials",
					icon: "boxes",
					iconColor: "text-stone-400",
					isFolder: true,
					items: [
						{
							id: "chemicals",
							text: "Chemicals",
							icon: "vial",
							iconColor: "text-purple-400",
							isFolder: false,
							items: [],
						},
						{
							id: "packaging",
							text: "Packaging",
							icon: "archive",
							iconColor: "text-yellow-400",
							isFolder: true,
							items: [
								{
									id: "bottles",
									text: "Bottles",
									icon: "wine-bottle",
									iconColor: "text-sky-400",
									isFolder: false,
									items: [],
								},
								{
									id: "labels",
									text: "Labels",
									icon: "tag",
									iconColor: "text-rose-400",
									isFolder: false,
									items: [],
								},
								{
									id: "cartons",
									text: "Cartons",
									icon: "box-open",
									iconColor: "text-amber-400",
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
				{
					id: "finished-products",
					text: "Finished Products",
					icon: "box-open",
					iconColor: "text-green-400",
					isFolder: true,
					items: [
						{
							id: "standard-products",
							text: "Standard Products",
							icon: "cube",
							iconColor: "text-blue-400",
							isFolder: false,
							items: [],
						},
						{
							id: "special-products",
							text: "Special Products",
							icon: "star",
							iconColor: "text-fuchsia-400",
							isFolder: false,
							items: [],
						},
						{
							id: "product-families",
							text: "Product Families",
							icon: "layer-group",
							iconColor: "text-indigo-400",
							isFolder: true,
							items: [
								{
									id: "cosmetics",
									text: "Cosmetics",
									icon: "spa",
									iconColor: "text-pink-400",
									isFolder: false,
									items: [],
								},
								{
									id: "detergents",
									text: "Detergents",
									icon: "soap",
									iconColor: "text-cyan-400",
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
			],
		},
		{
			id: "documents",
			text: "Documents",
			icon: "file-invoice",
			iconColor: "text-amber-400",
			isFolder: true,
			items: [
				{
					id: "purchase-documents",
					text: "Purchase",
					icon: "shopping-cart",
					iconColor: "text-green-400",
					isFolder: true,
					items: [
						{
							id: "purchase-orders",
							text: "Purchase Orders",
							icon: "file-alt",
							iconColor: "text-emerald-400",
							isFolder: false,
							items: [],
						},
						{
							id: "goods-receipts",
							text: "Goods Receipts",
							icon: "dolly",
							iconColor: "text-lime-400",
							isFolder: false,
							items: [],
						},
						{
							id: "supplier-invoices",
							text: "Supplier Invoices",
							icon: "file-invoice-dollar",
							iconColor: "text-yellow-400",
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "sale-documents",
					text: "Sale",
					icon: "cash-register",
					iconColor: "text-blue-400",
					isFolder: true,
					items: [
						{
							id: "sales-orders",
							text: "Sales Orders",
							icon: "receipt",
							iconColor: "text-sky-400",
							isFolder: false,
							items: [],
						},
						{
							id: "delivery-notes",
							text: "Delivery Notes",
							icon: "truck",
							iconColor: "text-indigo-400",
							isFolder: false,
							items: [],
						},
						{
							id: "customer-invoices",
							text: "Customer Invoices",
							icon: "file-invoice-dollar",
							iconColor: "text-cyan-400",
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "production-documents",
					text: "Production",
					icon: "industry",
					iconColor: "text-purple-400",
					isFolder: true,
					items: [
						{
							id: "production-orders",
							text: "Production Orders",
							icon: "tasks",
							iconColor: "text-violet-400",
							isFolder: false,
							items: [],
						},
						{
							id: "batch-records",
							text: "Batch Records",
							icon: "clipboard-check",
							iconColor: "text-fuchsia-400",
							isFolder: false,
							items: [],
						},
						{
							id: "work-centers",
							text: "Work Centers",
							icon: "cogs",
							iconColor: "text-slate-400",
							isFolder: true,
							items: [
								{
									id: "mixing",
									text: "Mixing",
									icon: "blender",
									iconColor: "text-orange-400",
									isFolder: false,
									items: [],
								},
								{
									id: "filling",
									text: "Filling",
									icon: "fill-drip",
									iconColor: "text-teal-400",
									isFolder: false,
									items: [],
								},
								{
									id: "packing",
									text: "Packing",
									icon: "boxes",
									iconColor: "text-amber-400",
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
				{
					id: "adjustment-documents",
					text: "Adjustment",
					icon: "sliders-h",
					iconColor: "text-rose-400",
					isFolder: true,
					items: [
						{
							id: "stock-adjustments",
							text: "Stock Adjustments",
							icon: "warehouse",
							iconColor: "text-red-400",
							isFolder: false,
							items: [],
						},
						{
							id: "lot-corrections",
							text: "Lot Corrections",
							icon: "edit",
							iconColor: "text-orange-400",
							isFolder: false,
							items: [],
						},
					],
				},
			],
		},
		{
			id: "laboratory",
			text: "Laboratory",
			icon: "flask",
			iconColor: "text-cyan-400",
			isFolder: true,
			items: [
				{
					id: "recipes",
					text: "Recipes",
					icon: "book-open",
					iconColor: "text-lime-400",
					isFolder: true,
					items: [
						{
							id: "active-recipes",
							text: "Active Recipes",
							icon: "check",
							iconColor: "text-green-400",
							isFolder: false,
							items: [],
						},
						{
							id: "draft-recipes",
							text: "Draft Recipes",
							icon: "pencil-alt",
							iconColor: "text-yellow-400",
							isFolder: false,
							items: [],
						},
						{
							id: "archived-recipes",
							text: "Archived Recipes",
							icon: "archive",
							iconColor: "text-slate-400",
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "quality-control",
					text: "Quality Control",
					icon: "microscope",
					iconColor: "text-purple-400",
					isFolder: true,
					items: [
						{
							id: "test-methods",
							text: "Test Methods",
							icon: "clipboard-list",
							iconColor: "text-blue-400",
							isFolder: false,
							items: [],
						},
						{
							id: "sample-results",
							text: "Sample Results",
							icon: "poll",
							iconColor: "text-teal-400",
							isFolder: false,
							items: [],
						},
						{
							id: "non-conformities",
							text: "Non-Conformities",
							icon: "exclamation-triangle",
							iconColor: "text-red-400",
							isFolder: false,
							items: [],
						},
					],
				},
			],
		},
		{
			id: "reports",
			text: "Reports",
			icon: "chart-bar",
			iconColor: "text-emerald-400",
			isFolder: true,
			items: [
				{
					id: "inventory-reports",
					text: "Inventory",
					icon: "warehouse",
					iconColor: "text-yellow-400",
					isFolder: true,
					items: [
						{
							id: "lot-balance",
							text: "Lot Balance",
							icon: "balance-scale",
							iconColor: "text-yellow-400",
							isFolder: false,
							items: [],
						},
						{
							id: "stock-valuation",
							text: "Stock Valuation",
							icon: "coins",
							iconColor: "text-amber-400",
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "traceability-reports",
					text: "Traceability",
					icon: "project-diagram",
					iconColor: "text-sky-400",
					isFolder: true,
					items: [
						{
							id: "lot-trace",
							text: "Lot Trace",
							icon: "route",
							iconColor: "text-sky-400",
							isFolder: false,
							items: [],
						},
						{
							id: "forward-trace",
							text: "Forward Trace",
							icon: "arrow-right",
							iconColor: "text-green-400",
							isFolder: false,
							items: [],
						},
						{
							id: "backward-trace",
							text: "Backward Trace",
							icon: "arrow-left",
							iconColor: "text-orange-400",
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "financial-reports",
					text: "Financial",
					icon: "chart-line",
					iconColor: "text-emerald-400",
					isFolder: true,
					items: [
						{
							id: "sales-analysis",
							text: "Sales Analysis",
							icon: "chart-pie",
							iconColor: "text-blue-400",
							isFolder: false,
							items: [],
						},
						{
							id: "purchase-analysis",
							text: "Purchase Analysis",
							icon: "chart-area",
							iconColor: "text-purple-400",
							isFolder: false,
							items: [],
						},
					],
				},
			],
		},
		{
			id: "settings",
			text: "Settings",
			icon: "cog",
			iconColor: "text-slate-400",
			isFolder: true,
			items: [
				{
					id: "system",
					text: "System",
					icon: "server",
					iconColor: "text-gray-400",
					isFolder: true,
					items: [
						{
							id: "users",
							text: "Users",
							icon: "user-cog",
							iconColor: "text-indigo-400",
							isFolder: false,
							items: [],
						},
						{
							id: "roles",
							text: "Roles",
							icon: "user-shield",
							iconColor: "text-purple-400",
							isFolder: false,
							items: [],
						},
						{
							id: "permissions",
							text: "Permissions",
							icon: "key",
							iconColor: "text-yellow-400",
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "master-data",
					text: "Master Data",
					icon: "database",
					iconColor: "text-blue-400",
					isFolder: true,
					items: [
						{
							id: "units",
							text: "Units",
							icon: "ruler",
							iconColor: "text-cyan-400",
							isFolder: false,
							items: [],
						},
						{
							id: "tax-rates",
							text: "Tax Rates",
							icon: "percent",
							iconColor: "text-green-400",
							isFolder: false,
							items: [],
						},
						{
							id: "currencies",
							text: "Currencies",
							icon: "coins",
							iconColor: "text-amber-400",
							isFolder: false,
							items: [],
						},
					],
				},
			],
		},
	],
};
