import type { MenuDataModel } from "menu-lib";

export const menuData: MenuDataModel = {
	mainHeaderText: "Manufacturing",
	subHeaderText: "System Menu",
	menuItems: [
		{
			id: "partners",
			text: "Partners",
			icon: "user-friends",
			iconColor: "#818cf8",
			order: 9990,
			isFolder: true,
			items: [
				{
					id: "suppliers",
					text: "Suppliers",
					icon: "truck-loading",
					iconColor: "#fbbf24",
					order: 9980,
					isFolder: true,
					items: [
						{
							id: "supplier-list",
							text: "Supplier List",
							icon: "list",
							iconColor: "#94a3b8",
							order: 9970,
							isFolder: false,
							items: [],
						},
						{
							id: "supplier-categories",
							text: "Supplier Categories",
							icon: "tags",
							iconColor: "#f472b6",
							order: 9960,
							isFolder: false,
							items: [],
						},
						{
							id: "supplier-contracts",
							text: "Contracts",
							icon: "file-signature",
							iconColor: "#a78bfa",
							order: 9950,
							isFolder: true,
							items: [
								{
									id: "active-supplier-contracts",
									text: "Active Contracts",
									icon: "check-circle",
									iconColor: "#4ade80",
									order: 9940,
									isFolder: false,
									items: [],
								},
								{
									id: "expired-supplier-contracts",
									text: "Expired Contracts",
									icon: "times-circle",
									iconColor: "#f87171",
									order: 9930,
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
				{
					id: "customers",
					text: "Customers",
					icon: "user-tag",
					iconColor: "#2dd4bf",
					order: 9920,
					isFolder: true,
					items: [
						{
							id: "customer-list",
							text: "Customer List",
							icon: "address-book",
							iconColor: "#60a5fa",
							order: 9910,
							isFolder: false,
							items: [],
						},
						{
							id: "customer-groups",
							text: "Customer Groups",
							icon: "users",
							iconColor: "#22d3ee",
							order: 9900,
							isFolder: false,
							items: [],
						},
						{
							id: "customer-pricing",
							text: "Pricing",
							icon: "money-bill-wave",
							iconColor: "#34d399",
							order: 9890,
							isFolder: true,
							items: [
								{
									id: "price-lists",
									text: "Price Lists",
									icon: "clipboard-list",
									iconColor: "#a3e635",
									order: 9880,
									isFolder: false,
									items: [],
								},
								{
									id: "discount-rules",
									text: "Discount Rules",
									icon: "percent",
									iconColor: "#fb923c",
									order: 9870,
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
			],
		},
		{
			id: "products",
			text: "Products",
			icon: "box",
			iconColor: "#fb923c",
			order: 9860,
			isFolder: true,
			items: [
				{
					id: "raw-materials",
					text: "Raw Materials",
					icon: "boxes",
					iconColor: "#a8a29e",
					order: 9850,
					isFolder: true,
					items: [
						{
							id: "chemicals",
							text: "Chemicals",
							icon: "vial",
							iconColor: "#c084fc",
							order: 9840,
							isFolder: false,
							items: [],
						},
						{
							id: "packaging",
							text: "Packaging",
							icon: "archive",
							iconColor: "#facc15",
							order: 9830,
							isFolder: true,
							items: [
								{
									id: "bottles",
									text: "Bottles",
									icon: "wine-bottle",
									iconColor: "#38bdf8",
									order: 9820,
									isFolder: false,
									items: [],
								},
								{
									id: "labels",
									text: "Labels",
									icon: "tag",
									iconColor: "#fb7185",
									order: 9810,
									isFolder: false,
									items: [],
								},
								{
									id: "cartons",
									text: "Cartons",
									icon: "box-open",
									iconColor: "#fbbf24",
									order: 9800,
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
				{
					id: "finished-products",
					text: "Finished Products",
					icon: "box-open",
					iconColor: "#4ade80",
					order: 9790,
					isFolder: true,
					items: [
						{
							id: "standard-products",
							text: "Standard Products",
							icon: "cube",
							iconColor: "#60a5fa",
							order: 9780,
							isFolder: false,
							items: [],
						},
						{
							id: "special-products",
							text: "Special Products",
							icon: "star",
							iconColor: "#e879f9",
							order: 9770,
							isFolder: false,
							items: [],
						},
						{
							id: "product-families",
							text: "Product Families",
							icon: "layer-group",
							iconColor: "#818cf8",
							order: 9760,
							isFolder: true,
							items: [
								{
									id: "cosmetics",
									text: "Cosmetics",
									icon: "spa",
									iconColor: "#f472b6",
									order: 9750,
									isFolder: false,
									items: [],
								},
								{
									id: "detergents",
									text: "Detergents",
									icon: "soap",
									iconColor: "#22d3ee",
									order: 9740,
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
			],
		},
		{
			id: "documents",
			text: "Documents",
			icon: "file-invoice",
			iconColor: "#fbbf24",
			order: 9730,
			isFolder: true,
			items: [
				{
					id: "purchase-documents",
					text: "Purchase",
					icon: "shopping-cart",
					iconColor: "#4ade80",
					order: 9720,
					isFolder: true,
					items: [
						{
							id: "purchase-orders",
							text: "Purchase Orders",
							icon: "file-alt",
							iconColor: "#34d399",
							order: 9710,
							isFolder: false,
							items: [],
						},
						{
							id: "goods-receipts",
							text: "Goods Receipts",
							icon: "dolly",
							iconColor: "#a3e635",
							order: 9700,
							isFolder: false,
							items: [],
						},
						{
							id: "supplier-invoices",
							text: "Supplier Invoices",
							icon: "file-invoice-dollar",
							iconColor: "#facc15",
							order: 9690,
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "sale-documents",
					text: "Sale",
					icon: "cash-register",
					iconColor: "#60a5fa",
					order: 9680,
					isFolder: true,
					items: [
						{
							id: "sales-orders",
							text: "Sales Orders",
							icon: "receipt",
							iconColor: "#38bdf8",
							order: 9670,
							isFolder: false,
							items: [],
						},
						{
							id: "delivery-notes",
							text: "Delivery Notes",
							icon: "truck",
							iconColor: "#818cf8",
							order: 9660,
							isFolder: false,
							items: [],
						},
						{
							id: "customer-invoices",
							text: "Customer Invoices",
							icon: "file-invoice-dollar",
							iconColor: "#22d3ee",
							order: 9650,
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "production-documents",
					text: "Production",
					icon: "industry",
					iconColor: "#c084fc",
					order: 9640,
					isFolder: true,
					items: [
						{
							id: "production-orders",
							text: "Production Orders",
							icon: "tasks",
							iconColor: "#a78bfa",
							order: 9630,
							isFolder: false,
							items: [],
						},
						{
							id: "batch-records",
							text: "Batch Records",
							icon: "clipboard-check",
							iconColor: "#e879f9",
							order: 9620,
							isFolder: false,
							items: [],
						},
						{
							id: "work-centers",
							text: "Work Centers",
							icon: "cogs",
							iconColor: "#94a3b8",
							order: 9610,
							isFolder: true,
							items: [
								{
									id: "mixing",
									text: "Mixing",
									icon: "blender",
									iconColor: "#fb923c",
									order: 9600,
									isFolder: false,
									items: [],
								},
								{
									id: "filling",
									text: "Filling",
									icon: "fill-drip",
									iconColor: "#2dd4bf",
									order: 9590,
									isFolder: false,
									items: [],
								},
								{
									id: "packing",
									text: "Packing",
									icon: "boxes",
									iconColor: "#fbbf24",
									order: 9580,
									isFolder: false,
									items: [],
								},
							],
						},
					],
				},
				{
					id: "adjustment-documents",
					text: "Adjustment",
					icon: "sliders-h",
					iconColor: "#fb7185",
					order: 9570,
					isFolder: true,
					items: [
						{
							id: "stock-adjustments",
							text: "Stock Adjustments",
							icon: "warehouse",
							iconColor: "#f87171",
							order: 9560,
							isFolder: false,
							items: [],
						},
						{
							id: "lot-corrections",
							text: "Lot Corrections",
							icon: "edit",
							iconColor: "#fb923c",
							order: 9550,
							isFolder: false,
							items: [],
						},
					],
				},
			],
		},
		{
			id: "laboratory",
			text: "Laboratory",
			icon: "flask",
			iconColor: "#22d3ee",
			order: 9540,
			isFolder: true,
			items: [
				{
					id: "recipes",
					text: "Recipes",
					icon: "book-open",
					iconColor: "#a3e635",
					order: 9530,
					isFolder: true,
					items: [
						{
							id: "active-recipes",
							text: "Active Recipes",
							icon: "check",
							iconColor: "#4ade80",
							order: 9520,
							isFolder: false,
							items: [],
						},
						{
							id: "draft-recipes",
							text: "Draft Recipes",
							icon: "pencil-alt",
							iconColor: "#facc15",
							order: 9510,
							isFolder: false,
							items: [],
						},
						{
							id: "archived-recipes",
							text: "Archived Recipes",
							icon: "archive",
							iconColor: "#94a3b8",
							order: 9500,
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "quality-control",
					text: "Quality Control",
					icon: "microscope",
					iconColor: "#c084fc",
					order: 9490,
					isFolder: true,
					items: [
						{
							id: "test-methods",
							text: "Test Methods",
							icon: "clipboard-list",
							iconColor: "#60a5fa",
							order: 9480,
							isFolder: false,
							items: [],
						},
						{
							id: "sample-results",
							text: "Sample Results",
							icon: "poll",
							iconColor: "#2dd4bf",
							order: 9470,
							isFolder: false,
							items: [],
						},
						{
							id: "non-conformities",
							text: "Non-Conformities",
							icon: "exclamation-triangle",
							iconColor: "#f87171",
							order: 9460,
							isFolder: false,
							items: [],
						},
					],
				},
			],
		},
		{
			id: "reports",
			text: "Reports",
			icon: "chart-bar",
			iconColor: "#34d399",
			order: 9450,
			isFolder: true,
			items: [
				{
					id: "inventory-reports",
					text: "Inventory",
					icon: "warehouse",
					iconColor: "#facc15",
					order: 9440,
					isFolder: true,
					items: [
						{
							id: "lot-balance",
							text: "Lot Balance",
							icon: "balance-scale",
							iconColor: "#facc15",
							order: 9430,
							isFolder: false,
							items: [],
						},
						{
							id: "stock-valuation",
							text: "Stock Valuation",
							icon: "coins",
							iconColor: "#fbbf24",
							order: 9420,
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "traceability-reports",
					text: "Traceability",
					icon: "project-diagram",
					iconColor: "#38bdf8",
					order: 9410,
					isFolder: true,
					items: [
						{
							id: "lot-trace",
							text: "Lot Trace",
							icon: "route",
							iconColor: "#38bdf8",
							order: 9400,
							isFolder: false,
							items: [],
						},
						{
							id: "forward-trace",
							text: "Forward Trace",
							icon: "arrow-right",
							iconColor: "#4ade80",
							order: 9390,
							isFolder: false,
							items: [],
						},
						{
							id: "backward-trace",
							text: "Backward Trace",
							icon: "arrow-left",
							iconColor: "#fb923c",
							order: 9380,
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "financial-reports",
					text: "Financial",
					icon: "chart-line",
					iconColor: "#34d399",
					order: 9370,
					isFolder: true,
					items: [
						{
							id: "sales-analysis",
							text: "Sales Analysis",
							icon: "chart-pie",
							iconColor: "#60a5fa",
							order: 9360,
							isFolder: false,
							items: [],
						},
						{
							id: "purchase-analysis",
							text: "Purchase Analysis",
							icon: "chart-area",
							iconColor: "#c084fc",
							order: 9350,
							isFolder: false,
							items: [],
						},
					],
				},
			],
		},
		{
			id: "settings",
			text: "Settings",
			icon: "cog",
			iconColor: "#94a3b8",
			order: 9340,
			isFolder: true,
			items: [
				{
					id: "system",
					text: "System",
					icon: "server",
					iconColor: "#9ca3af",
					order: 9330,
					isFolder: true,
					items: [
						{
							id: "users",
							text: "Users",
							icon: "user-cog",
							iconColor: "#818cf8",
							order: 9320,
							isFolder: false,
							items: [],
						},
						{
							id: "roles",
							text: "Roles",
							icon: "user-shield",
							iconColor: "#c084fc",
							order: 9310,
							isFolder: false,
							items: [],
						},
						{
							id: "permissions",
							text: "Permissions",
							icon: "key",
							iconColor: "#facc15",
							order: 9300,
							isFolder: false,
							items: [],
						},
					],
				},
				{
					id: "master-data",
					text: "Master Data",
					icon: "database",
					iconColor: "#60a5fa",
					order: 9290,
					isFolder: true,
					items: [
						{
							id: "units",
							text: "Units",
							icon: "ruler",
							iconColor: "#22d3ee",
							order: 9280,
							isFolder: false,
							items: [],
						},
						{
							id: "tax-rates",
							text: "Tax Rates",
							icon: "percent",
							iconColor: "#4ade80",
							order: 9270,
							isFolder: false,
							items: [],
						},
						{
							id: "currencies",
							text: "Currencies",
							icon: "coins",
							iconColor: "#fbbf24",
							order: 9260,
							isFolder: false,
							items: [],
						},
					],
				},
			],
		},
	],
};
